---
name: Build, test, and upload PyPI package

on:
    push:
        branches:
            - main
        tags:
            - "v*"
    pull_request:
        branches:
            - main
    release:
        types:
            - published

jobs:
    build-package:
        name: Build and check packages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # for setuptools-scm
                  fetch-depth: 0
                  submodules: true

            - uses: hynek/build-and-inspect-python-package@v2
              with:
                  skip-wheel: 'false'

    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # macos-13 is an intel runner, macos-14 is apple silicon
                os: [ubuntu-latest, ubuntu-24.04-arm, macos-14]

        steps:
            - uses: actions/checkout@v4
              with:
                  # for setuptools-scm
                  fetch-depth: 0
                  submodules: true

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.22.0

            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                  path: ./wheelhouse/*.whl

    build_sdist:
        name: Build source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # for setuptools-scm
                  fetch-depth: 0
                  submodules: true

            - name: Build sdist
              run: pipx run build --sdist

            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-sdist
                  path: dist/*.tar.gz

    publish-test-pypi:
        name: Publish packages to test.pypi.org
        # environment: publish-test-pypi
        permissions:
            id-token: write
        if: |
            github.repository_owner == 'instructlab' && (
                github.event.action == 'published' ||
                (github.event_name == 'push' && github.ref == 'refs/heads/main')
            )
        runs-on: ubuntu-latest
        needs: [build_wheels, build_sdist]

        steps:
            - name: Fetch build artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: cibw-*
                  path: dist
                  merge-multiple: true

            - name: Upload to Test PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/

    publish-pypi:
        name: Publish release to pypi.org
        # environment: publish-pypi
        permissions:
            contents: write
            id-token: write
        if: |
            github.repository_owner == 'instructlab' && github.event.action == 'published'
        runs-on: ubuntu-latest
        needs: [build_wheels, build_sdist]

        steps:
            - name: Fetch build artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: cibw-*
                  path: dist
                  merge-multiple: true

            - uses: sigstore/gh-action-sigstore-python@v3.0.0
              with:
                  inputs: >-
                      ./dist/*.tar.gz
                      ./dist/*.whl

            - name: Upload artifact signatures to GitHub Release
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              run: >-
                  gh release upload '${{ github.ref_name }}' dist/* --repo '${{ github.repository }}'

            # PyPI does not accept .sigstore artifacts and
            # gh-action-pypi-publish has no option to ignore them.
            - name: Remove sigstore signatures before uploading to PyPI
              run: rm ./dist/*.sigstore

            - name: Upload to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
